name: BossPlugin
version: 3.5
api: 3.11.0
author: HmmHmmmmm
main: hmmhmmmm\boss\Boss
website: https://github.com/HmmHmmmm/BossPlugin
depend:
- Slapper
- PureEntitiesX

permissions:
  boss:
    default: false
    children:
      boss.command:
        default: op